// C# / Unity exporter (PRO) — typed ScriptableObject with configuration for all nodes

import type { GSSGraph } from '../../types/graph'
import { NodeType } from '../../types/graph'

function cs(v: unknown): string {
  if (typeof v === 'string') return `"${v.replace(/"/g, '\\"')}"`
  if (typeof v === 'number') return Number.isInteger(v) ? `${v}` : `${v}f`
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return 'null'
}

export function exportCSharp(
  graph: GSSGraph,
): string {
  const cls = graph.name.replace(/[^a-zA-Z0-9]/g, '') || 'EconomyConfig'
  const ts  = new Date().toISOString()

  const pools     = graph.nodes.filter(n => n.type === NodeType.POOL)
  const sources   = graph.nodes.filter(n => n.type === NodeType.SOURCE)
  const converters = graph.nodes.filter(n => n.type === NodeType.CONVERTER)
  const drains    = graph.nodes.filter(n => n.type === NodeType.DRAIN)
  const gates     = graph.nodes.filter(n => n.type === NodeType.GATE)
  const chances   = graph.nodes.filter(n => n.type === NodeType.CHANCE)
  const splitters = graph.nodes.filter(n => n.type === NodeType.SPLITTER)

  const lines: string[] = []
  lines.push(`// Generated by GSS ${graph.version} — Game Systems Simulator`)
  lines.push(`// Graph: ${graph.name}  |  Generated: ${ts}`)
  lines.push(`// PRO export — C# / Unity`)
  lines.push('')
  lines.push('using System;')
  lines.push('using System.Collections.Generic;')
  lines.push('using UnityEngine;')
  lines.push('')

  // ---- Pool data struct ----
  lines.push('[Serializable]')
  lines.push('public struct GSSPool {')
  lines.push('    public string id;')
  lines.push('    public string resource;')
  lines.push('    public float capacity;')
  lines.push('    public float initialAmount;')
  lines.push('}')
  lines.push('')

  // ---- Source data struct ----
  lines.push('[Serializable]')
  lines.push('public struct GSSSource {')
  lines.push('    public string id;')
  lines.push('    public string resource;')
  lines.push('    public float rate;')
  lines.push('}')
  lines.push('')

  // ---- Connection struct ----
  lines.push('[Serializable]')
  lines.push('public struct GSSConnection {')
  lines.push('    public string fromNode;')
  lines.push('    public string toNode;')
  lines.push('}')
  lines.push('')

  // ---- Main ScriptableObject ----
  lines.push('/// <summary>')
  lines.push(`/// Economy configuration: ${graph.name}`)
  lines.push('/// Import into Unity via Assets → Create → GSS → Economy Config')
  lines.push('/// </summary>')
  lines.push('[CreateAssetMenu(fileName = "EconomyConfig", menuName = "GSS/Economy Config")]')
  lines.push(`public class ${cls} : ScriptableObject`)
  lines.push('{')

  // Pools
  if (pools.length > 0) {
    lines.push('    [Header("Pools")]')
    lines.push('    public GSSPool[] pools = new GSSPool[]')
    lines.push('    {')
    for (const n of pools) {
      const d = n.data as { resource?: string; capacity?: number; initial_amount?: number }
      lines.push(`        new GSSPool { id = ${cs(n.id)}, resource = ${cs(d.resource ?? '')}, capacity = ${cs(d.capacity ?? 100)}, initialAmount = ${cs(d.initial_amount ?? 0)} },`)
    }
    lines.push('    };')
    lines.push('')
  }

  // Sources
  if (sources.length > 0) {
    lines.push('    [Header("Sources")]')
    lines.push('    public GSSSource[] sources = new GSSSource[]')
    lines.push('    {')
    for (const n of sources) {
      const d = n.data as { resource?: string; rate?: number }
      lines.push(`        new GSSSource { id = ${cs(n.id)}, resource = ${cs(d.resource ?? '')}, rate = ${cs(d.rate ?? 1)} },`)
    }
    lines.push('    };')
    lines.push('')
  }

  // Connections
  if (graph.connections.length > 0) {
    lines.push('    [Header("Connections")]')
    lines.push('    public GSSConnection[] connections = new GSSConnection[]')
    lines.push('    {')
    for (const c of graph.connections) {
      lines.push(`        new GSSConnection { fromNode = ${cs(c.from_node)}, toNode = ${cs(c.to_node)} },`)
    }
    lines.push('    };')
    lines.push('')
  }

  // Metadata comments for unsupported node types
  const unsupported = [...converters, ...drains, ...gates, ...chances, ...splitters]
  if (unsupported.length > 0) {
    lines.push('    // Additional node types (manual implementation required):')
    for (const n of unsupported) {
      const typeName = ['Pool','Source','Converter','Drain','Gate','Chance','','Splitter'][n.type] ?? 'Unknown'
      lines.push(`    //   [${typeName}] ${n.id} — "${n.label}"`)
    }
    lines.push('')
  }

  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
