// GDScript / Godot 4 exporter (PRO) — typed Resource s @export anotacemi

import type { GSSGraph } from '../../types/graph'
import { NodeType } from '../../types/graph'

function gdVal(v: unknown): string {
  if (typeof v === 'string') return `"${v.replace(/"/g, '\\"')}"`
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? 'true' : 'false'
  return 'null'
}

export function exportGDScript(
  graph: GSSGraph,
): string {
  const className = graph.name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, '_$&') || 'EconomyConfig'
  const ts = new Date().toISOString()

  const pools     = graph.nodes.filter(n => n.type === NodeType.POOL)
  const sources   = graph.nodes.filter(n => n.type === NodeType.SOURCE)
  const converters = graph.nodes.filter(n => n.type === NodeType.CONVERTER)
  const drains    = graph.nodes.filter(n => n.type === NodeType.DRAIN)
  const gates     = graph.nodes.filter(n => n.type === NodeType.GATE)
  const chances   = graph.nodes.filter(n => n.type === NodeType.CHANCE)
  const splitters = graph.nodes.filter(n => n.type === NodeType.SPLITTER)

  const L: string[] = []

  L.push(`# Generated by GSS ${graph.version} — Game Systems Simulator`)
  L.push(`# Graph: ${graph.name}  |  Generated: ${ts}`)
  L.push(`# PRO export — GDScript / Godot 4`)
  L.push('')
  L.push(`class_name ${className}`)
  L.push('extends Resource')
  L.push('')

  // Pools
  if (pools.length > 0) {
    L.push('# — Pools —')
    for (const n of pools) {
      const d = n.data as { resource?: string; capacity?: number; initial_amount?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Pool: ${n.label}")`)
      L.push(`@export var ${safe}_resource: String = ${gdVal(d.resource ?? '')}`)
      L.push(`@export var ${safe}_capacity: float = ${gdVal(d.capacity ?? 100)}`)
      L.push(`@export var ${safe}_initial: float = ${gdVal(d.initial_amount ?? 0)}`)
      L.push('')
    }
  }

  // Sources
  if (sources.length > 0) {
    L.push('# — Sources —')
    for (const n of sources) {
      const d = n.data as { resource?: string; rate?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Source: ${n.label}")`)
      L.push(`@export var ${safe}_resource: String = ${gdVal(d.resource ?? '')}`)
      L.push(`@export var ${safe}_rate: float = ${gdVal(d.rate ?? 1)}`)
      L.push('')
    }
  }

  // Converters
  if (converters.length > 0) {
    L.push('# — Converters —')
    for (const n of converters) {
      const d = n.data as { input_resource?: string; input_amount?: number; output_resource?: string; output_amount?: number; cycle_time?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Converter: ${n.label}")`)
      L.push(`@export var ${safe}_in_resource: String = ${gdVal(d.input_resource ?? '')}`)
      L.push(`@export var ${safe}_in_amount: float = ${gdVal(d.input_amount ?? 1)}`)
      L.push(`@export var ${safe}_out_resource: String = ${gdVal(d.output_resource ?? '')}`)
      L.push(`@export var ${safe}_out_amount: float = ${gdVal(d.output_amount ?? 1)}`)
      L.push(`@export var ${safe}_cycle_time: float = ${gdVal(d.cycle_time ?? 1)}`)
      L.push('')
    }
  }

  // Drains
  if (drains.length > 0) {
    L.push('# — Drains —')
    for (const n of drains) {
      const d = n.data as { resource?: string; rate?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Drain: ${n.label}")`)
      L.push(`@export var ${safe}_resource: String = ${gdVal(d.resource ?? '')}`)
      L.push(`@export var ${safe}_rate: float = ${gdVal(d.rate ?? 1)}`)
      L.push('')
    }
  }

  // Gates
  if (gates.length > 0) {
    L.push('# — Gates —')
    const OPS = ['>', '>=', '<', '<=', '==', '!=']
    for (const n of gates) {
      const d = n.data as { variable?: string; operator?: number; value?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      const op = OPS[d.operator ?? 0] ?? '>'
      L.push(`@export_group("Gate: ${n.label}")`)
      L.push(`@export var ${safe}_variable: String = ${gdVal(d.variable ?? '')}`)
      L.push(`@export var ${safe}_operator: String = ${gdVal(op)}`)
      L.push(`@export var ${safe}_threshold: float = ${gdVal(d.value ?? 0)}`)
      L.push('')
    }
  }

  // Chances
  if (chances.length > 0) {
    L.push('# — Chance nodes —')
    for (const n of chances) {
      const d = n.data as { success_chance?: number }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Chance: ${n.label}")`)
      L.push(`@export_range(0, 100) var ${safe}_success_chance: float = ${gdVal(d.success_chance ?? 50)}`)
      L.push('')
    }
  }

  // Splitters
  if (splitters.length > 0) {
    L.push('# — Splitters —')
    for (const n of splitters) {
      const d = n.data as { split_mode?: number; output_count?: number; weights?: string }
      const safe = n.id.replace(/[^a-zA-Z0-9_]/g, '_')
      L.push(`@export_group("Splitter: ${n.label}")`)
      L.push(`@export_enum("Equal", "Weighted") var ${safe}_mode: int = ${gdVal(d.split_mode ?? 0)}`)
      L.push(`@export var ${safe}_outputs: int = ${gdVal(d.output_count ?? 2)}`)
      L.push(`@export var ${safe}_weights: String = ${gdVal(d.weights ?? '1,1')}`)
      L.push('')
    }
  }

  // Connections jako Dictionary array
  if (graph.connections.length > 0) {
    L.push('# — Connections —')
    L.push('@export var connections: Array[Dictionary] = [')
    for (const c of graph.connections) {
      L.push(`\t{ "from": ${gdVal(c.from_node)}, "to": ${gdVal(c.to_node)} },`)
    }
    L.push(']')
    L.push('')
  }

  return L.join('\n')
}
