// TypeScript / Web exporter (PRO) — typed interfaces + immutable config objekty

import type { GSSGraph } from '../../types/graph'
import { NodeType } from '../../types/graph'

function tsVal(v: unknown): string {
  return JSON.stringify(v)
}

function safeName(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, '_').replace(/^([0-9])/, '_$1')
}

export function exportTypeScript(
  graph: GSSGraph,
): string {
  const CONST = graph.name.replace(/[^a-zA-Z0-9]/g, '_').toUpperCase() || 'ECONOMY_CONFIG'
  const ts = new Date().toISOString()

  const pools      = graph.nodes.filter(n => n.type === NodeType.POOL)
  const sources    = graph.nodes.filter(n => n.type === NodeType.SOURCE)
  const converters = graph.nodes.filter(n => n.type === NodeType.CONVERTER)
  const drains     = graph.nodes.filter(n => n.type === NodeType.DRAIN)
  const gates      = graph.nodes.filter(n => n.type === NodeType.GATE)
  const chances    = graph.nodes.filter(n => n.type === NodeType.CHANCE)
  const splitters  = graph.nodes.filter(n => n.type === NodeType.SPLITTER)

  const L: string[] = []

  L.push(`// Generated by GSS ${graph.version} \u2014 Game Systems Simulator`)
  L.push(`// Graph: ${graph.name}  |  Generated: ${ts}`)
  L.push(`// PRO export \u2014 TypeScript / Web / Node.js`)
  L.push('')

  // Interfaces
  L.push('// \u2014\u2014\u2014 Interfaces \u2014\u2014\u2014')
  L.push('export interface GSSPoolConfig {')
  L.push('  readonly id: string')
  L.push('  readonly resource: string')
  L.push('  readonly capacity: number')
  L.push('  readonly initialAmount: number')
  L.push('}')
  L.push('')
  L.push('export interface GSSSourceConfig {')
  L.push('  readonly id: string')
  L.push('  readonly resource: string')
  L.push('  readonly rate: number')
  L.push('}')
  L.push('')
  L.push('export interface GSSConverterConfig {')
  L.push('  readonly id: string')
  L.push('  readonly inputResource: string')
  L.push('  readonly inputAmount: number')
  L.push('  readonly outputResource: string')
  L.push('  readonly outputAmount: number')
  L.push('  readonly cycleTime: number')
  L.push('}')
  L.push('')
  L.push('export interface GSSDrainConfig {')
  L.push('  readonly id: string')
  L.push('  readonly resource: string')
  L.push('  readonly rate: number')
  L.push('}')
  L.push('')
  L.push('export interface GSSConnectionConfig {')
  L.push('  readonly fromNode: string')
  L.push('  readonly toNode: string')
  L.push('}')
  L.push('')
  L.push('export interface GSSEconomyConfig {')
  L.push('  readonly name: string')
  L.push('  readonly version: string')
  L.push('  readonly pools: readonly GSSPoolConfig[]')
  L.push('  readonly sources: readonly GSSSourceConfig[]')
  L.push('  readonly converters: readonly GSSConverterConfig[]')
  L.push('  readonly drains: readonly GSSDrainConfig[]')
  L.push('  readonly connections: readonly GSSConnectionConfig[]')
  L.push('}')
  L.push('')

  // Data
  L.push('// \u2014\u2014\u2014 Config data \u2014\u2014\u2014')
  L.push(`export const ${CONST}: GSSEconomyConfig = {`)
  L.push(`  name: ${tsVal(graph.name)},`)
  L.push(`  version: ${tsVal(graph.version)},`)

  // Pools
  L.push('  pools: [')
  for (const n of pools) {
    const d = n.data as { resource?: string; capacity?: number; initial_amount?: number }
    L.push(`    { id: ${tsVal(n.id)}, resource: ${tsVal(d.resource ?? '')}, capacity: ${d.capacity ?? 100}, initialAmount: ${d.initial_amount ?? 0} },`)
  }
  L.push('  ],') 

  // Sources
  L.push('  sources: [')
  for (const n of sources) {
    const d = n.data as { resource?: string; rate?: number }
    L.push(`    { id: ${tsVal(n.id)}, resource: ${tsVal(d.resource ?? '')}, rate: ${d.rate ?? 1} },`)
  }
  L.push('  ],')

  // Converters
  L.push('  converters: [')
  for (const n of converters) {
    const d = n.data as { input_resource?: string; input_amount?: number; output_resource?: string; output_amount?: number; cycle_time?: number }
    L.push(`    { id: ${tsVal(n.id)}, inputResource: ${tsVal(d.input_resource ?? '')}, inputAmount: ${d.input_amount ?? 1}, outputResource: ${tsVal(d.output_resource ?? '')}, outputAmount: ${d.output_amount ?? 1}, cycleTime: ${d.cycle_time ?? 1} },`)
  }
  L.push('  ],')

  // Drains
  L.push('  drains: [')
  for (const n of drains) {
    const d = n.data as { resource?: string; rate?: number }
    L.push(`    { id: ${tsVal(n.id)}, resource: ${tsVal(d.resource ?? '')}, rate: ${d.rate ?? 1} },`)
  }
  L.push('  ],')

  // Connections
  L.push('  connections: [')
  for (const c of graph.connections) {
    L.push(`    { fromNode: ${tsVal(c.from_node)}, toNode: ${tsVal(c.to_node)} },`)
  }
  L.push('  ],')

  L.push('} as const')
  L.push('')

  // Helper komentáře pro neexportované typy
  const extras = [...gates, ...chances, ...splitters]
  if (extras.length > 0) {
    L.push('// Gate, Chance and Splitter nodes require runtime logic — see GSS documentation.')
    for (const n of extras) {
      const typeName = ['Pool','Source','Converter','Drain','Gate','Chance','','Splitter'][n.type] ?? ''
      L.push(`// [${typeName}] ${n.id} \u2014 "${n.label}"`)
    }
    L.push('')
  }

  // Rychlý startovní helper
  L.push('// \u2014\u2014\u2014 Helper for easy lookup \u2014\u2014\u2014')
  if (pools.length > 0) {
    L.push(`export const POOLS = Object.fromEntries(`)
    L.push(`  ${CONST}.pools.map(p => [p.id, p])`)
    L.push(') as Record<string, GSSPoolConfig>')
    L.push('')
  }
  if (sources.length > 0) {
    L.push(`export const SOURCES = Object.fromEntries(`)
    L.push(`  ${CONST}.sources.map(s => [s.id, s])`)
    L.push(') as Record<string, GSSSourceConfig>')
    L.push('')
  }

  // Individuální named exporty pro každý Pool
  if (pools.length > 0) {
    L.push('// \u2014\u2014\u2014 Named pool constants \u2014\u2014\u2014')
    for (const n of pools) {
      const d = n.data as { resource?: string; capacity?: number; initial_amount?: number }
      L.push(`export const POOL_${safeName(n.id).toUpperCase()} = { id: ${tsVal(n.id)}, resource: ${tsVal(d.resource ?? '')}, capacity: ${d.capacity ?? 100}, initialAmount: ${d.initial_amount ?? 0} } as const`)
    }
    L.push('')
  }

  return L.join('\n')
}
