// ExportPanel — GSS JSON (free) + PRO format exports via Tauri save dialog

import { useState } from 'react'
import { platform } from '../../platform'
import { useGraphStore } from '../../store/graphStore'
import { useSimulationStore } from '../../store/simulationStore'
import { useLicenseStore } from '../../store/licenseStore'
import { exportGSSJson } from '../../core/exporters/json'
import { exportCSV } from '../../core/exporters/csv'
import { reportToCSV } from '../../core/ScenarioRunner'
import { buildDiagnosticsBundle, bundleToJSON } from '../../core/DiagnosticsExporter'
import { exportCSharp } from '../../core/exporters/csharp'
import { exportGDScript } from '../../core/exporters/gdscript'
import { exportTypeScript } from '../../core/exporters/typescript'
import type { GSSGraph } from '../../types/graph'
import type { RunReport, VerdictReport } from '../../types/simulation'
import { APP_VERSION } from '../../core/UpdateChecker'

export function buildPDFHtml(graph: GSSGraph, report: RunReport, verdict: VerdictReport | null): string {
  const pools = Object.entries(report.summary.final_values)
    .map(([id, v]) => `<tr><td>${id}</td><td>${v.toFixed(2)}</td><td>${(report.summary.min_values[id] ?? 0).toFixed(2)}</td><td>${(report.summary.max_values[id] ?? 0).toFixed(2)}</td></tr>`)
    .join('')
  return `<!DOCTYPE html><html><head><title>GSS Report — ${graph.name}</title>
  <style>body{font-family:sans-serif;margin:2rem;color:#111}h1{color:#6366f1}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccc;padding:6px 10px;text-align:left}th{background:#f0f0f0}@media print{body{margin:0}}</style>
  </head><body>
  <h1>GSS Economy Report</h1>
  <h2>${graph.name}</h2>
  <p>Nodes: ${graph.nodes.length} | Ticks: ${report.summary.total_ticks} | Duration: ${report.summary.elapsed.toFixed(1)}ms</p>
  ${verdict ? `<p><strong>Verdict:</strong> ${verdict.verdict.state} | Health: ${verdict.health_score.total}/100</p>` : ''}
  <h3>Final Pool Values</h3>
  <table><tr><th>Pool</th><th>Final</th><th>Min</th><th>Max</th></tr>${pools}</table>
  <p style="margin-top:2rem;color:#888;font-size:12px">Generated by GSS v${APP_VERSION} — ${new Date().toLocaleString()}</p>
  </body></html>`
}

export function buildWebShareHtml(graph: GSSGraph, report: RunReport | null): string {
  const nodeList = graph.nodes.map(n => `<li><strong>${n.label}</strong> (type ${n.type})</li>`).join('')
  const connList = graph.connections.map(c => `<li>${c.from_node} → ${c.to_node}</li>`).join('')
  const simData  = report
    ? `<h2>Simulation Results</h2><p>Ticks: ${report.summary.total_ticks} | Elapsed: ${report.summary.elapsed.toFixed(1)}ms</p><pre>${JSON.stringify(report.summary.final_values, null, 2)}</pre>`
    : '<p><em>No simulation data.</em></p>'
  return `<!DOCTYPE html><html><head><title>GSS — ${graph.name}</title>
  <style>body{font-family:sans-serif;margin:2rem;max-width:900px;color:#e2e8f0;background:#0a0a14}h1,h2{color:#6366f1}pre{background:#1e1e2e;padding:1rem;border-radius:8px;overflow:auto}ul{padding-left:1.5rem}</style>
  </head><body>
  <h1>🎮 GSS — ${graph.name}</h1>
  <p>${graph.description || 'Economy simulation project'}</p>
  <h2>Graph</h2>
  <p>${graph.nodes.length} nodes, ${graph.connections.length} connections</p>
  <ul>${nodeList}</ul>
  <h2>Connections</h2><ul>${connList}</ul>
  ${simData}
  <hr><p style="color:#555;font-size:12px">Exported from GSS v${APP_VERSION} — ${new Date().toLocaleString()}</p>
  </body></html>`
}

interface ExportFormat {
  id: string
  label: string
  ext: string
  pro: boolean
  generate: () => string
}

export function ExportPanel() {
  const graph        = useGraphStore((s) => s.graph)
  const reportA       = useSimulationStore((s) => s.reportA)
  const verdictReport = useSimulationStore((s) => s.verdictReport)
  const validIssues   = useSimulationStore((s) => s.issues)
  const isPro  = useLicenseStore((s) => s.license?.isPro ?? false)
  const [status, setStatus] = useState<string | null>(null)
  const [error,  setError]  = useState<string | null>(null)

  const formats: ExportFormat[] = [
    {
      id: 'gss',
      label: '.gss JSON',
      ext: 'gss',
      pro: false,
      generate: () => exportGSSJson(graph),
    },
    {
      id: 'csv',
      label: 'CSV (tick data)',
      ext: 'csv',
      pro: false,
      generate: () => (reportA ? exportCSV(graph, reportA) : ''),
    },
    {
      id: 'csv_report',
      label: 'CSV (scenario report)',
      ext: 'csv',
      pro: false,
      generate: () => (reportA ? reportToCSV(reportA) : ''),
    },
    {
      id: 'csharp',
      label: 'C# / Unity',
      ext: 'cs',
      pro: true,
      generate: () => exportCSharp(graph),
    },
    {
      id: 'gdscript',
      label: 'GDScript / Godot 4',
      ext: 'gd',
      pro: true,
      generate: () => exportGDScript(graph),
    },
    {
      id: 'typescript',
      label: 'TypeScript / Web',
      ext: 'ts',
      pro: true,
      generate: () => exportTypeScript(graph),
    },
    {
      id: 'diagnostics',
      label: 'Diagnostics Bundle (JSON)',
      ext: 'json',
      pro: false,
      generate: () => {
        const bundle = buildDiagnosticsBundle(
          graph,
          reportA ? [reportA] : [],
          validIssues,
        )
        return bundleToJSON(bundle)
      },
    },
  ]

  async function handleExport(fmt: ExportFormat) {
    if (fmt.pro && !isPro) {
      setError(`${fmt.label} export requires GSS PRO.`)
      return
    }
    if ((fmt.id === 'csv' || fmt.id === 'csv_report') && !reportA) {
      setError('Run simulation first to export CSV data.')
      return
    }
    try {
      setStatus(null)
      setError(null)
      const content = fmt.generate()
      const defaultName = `${graph.name.replace(/\s+/g, '_')}.${fmt.ext}`
      const savedName = await platform.saveFile([fmt.ext], defaultName, content)
      if (!savedName) return
      setStatus(`Saved: ${savedName.split(/[\\/]/).pop()}`)
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err))
    }
  }

  function exportPDFReport() {
    if (!reportA) { setError('Run simulation first to export the PDF report.'); return }
    const html = buildPDFHtml(graph, reportA, verdictReport)
    const win = window.open('', '_blank', 'width=900,height=700')
    if (!win) { setError('Popup blocked — please allow popups for GSS.'); return }
    win.document.write(html)
    win.document.close()
    setTimeout(() => win.print(), 400)
    setStatus('Print dialog opened.')
  }

  function exportWebShare() {
    const html = buildWebShareHtml(graph, reportA)
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `${graph.name.replace(/\s+/g, '_')}_share.html`
    a.click()
    setTimeout(() => URL.revokeObjectURL(url), 2000)
    setStatus('Web Share HTML downloaded.')
  }

  return (
    <div className="flex flex-col gap-4 max-w-lg">
      <h2 className="text-sm font-semibold text-white/80">Export</h2>

      {/* PDF + Web Share row */}
      <div className="flex gap-2">
        <button
          onClick={exportPDFReport}
          disabled={!isPro}
          title={!isPro ? 'Requires GSS PRO' : 'Export simulation results as PDF'}
          className="flex-1 flex items-center justify-between p-3 bg-card border border-border rounded-lg disabled:opacity-40 disabled:cursor-not-allowed hover:border-white/20 transition-colors"
        >
          <div className="flex items-center gap-2">
            <span className="text-xs text-white">📄 PDF Report</span>
            <span className="px-1.5 py-0.5 bg-accent/20 text-accent text-[9px] rounded font-semibold">PRO</span>
          </div>
          <span className="text-xs text-white/50">{!isPro ? '🔒' : '↓'}</span>
        </button>
        <button
          onClick={exportWebShare}
          disabled={!isPro}
          title={!isPro ? 'Requires GSS PRO' : 'Export as shareable standalone HTML'}
          className="flex-1 flex items-center justify-between p-3 bg-card border border-border rounded-lg disabled:opacity-40 disabled:cursor-not-allowed hover:border-white/20 transition-colors"
        >
          <div className="flex items-center gap-2">
            <span className="text-xs text-white">🌐 Web Share</span>
            <span className="px-1.5 py-0.5 bg-accent/20 text-accent text-[9px] rounded font-semibold">PRO</span>
          </div>
          <span className="text-xs text-white/50">{!isPro ? '🔒' : '↓'}</span>
        </button>
      </div>

      <div className="flex flex-col gap-2">
        {formats.map((fmt) => {
          const locked = fmt.pro && !isPro
          return (
            <div
              key={fmt.id}
              className="flex items-center justify-between p-3 bg-card border border-border rounded-lg"
            >
              <div className="flex items-center gap-2">
                <span className="text-xs text-white">{fmt.label}</span>
                {fmt.pro && (
                  <span className="px-1.5 py-0.5 bg-accent/20 text-accent text-[9px] rounded font-semibold">
                    PRO
                  </span>
                )}
              </div>
              <button
                onClick={() => handleExport(fmt)}
                disabled={locked}
                className="px-3 py-1.5 text-xs rounded transition-colors disabled:opacity-40 disabled:cursor-not-allowed bg-border hover:bg-border/70 text-white"
              >
                {locked ? '🔒 Upgrade' : 'Export'}
              </button>
            </div>
          )
        })}
      </div>

      {status && (
        <div className="p-2 bg-green-400/10 border border-green-400/20 rounded text-green-400 text-xs">
          ✓ {status}
        </div>
      )}
      {error && (
        <div className="p-2 bg-red-400/10 border border-red-400/20 rounded text-red-400 text-xs">
          {error}
        </div>
      )}
    </div>
  )
}
